In [1]:
!mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 0.501 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.6    np23py313h124dbc7_0  emscripten-forge-4x
+ python-tzdata  2026.5   pyh5ded981_0         conda-forge
- pip            26.2.1   pyh145f28c_0         conda-forge

In [2]:
import pandas as pd

In [3]:
datafile=pd.read_csv ("https://raw.githubusercontent.com/Psyc3000A/Data/refs/heads/main/sleep.csv")

In [4]:
datafile.groupby('group').describe()

          A                                                extra        ...  \
      count  mean      std   min    25%   50%    75%   max count  mean  ...
group                                                                   ...
1      10.0   5.5  3.02765   1.0   3.25   5.5   7.75  10.0  10.0  0.75  ...
2      10.0  15.5  3.02765  11.0  13.25  15.5  17.75  20.0  10.0  2.33  ...

                    ID
        75%  max count mean      std  min   25%  50%   75%   max
group
1      1.70  3.7  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0
2      4.15  5.5  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0

[2 rows x 24 columns]

In [5]:
datafile.groupby("group")["extra"].agg(["count", "mean", "std", "skew"])

       count  mean       std      skew
group
1         10  0.75  1.789010  0.580921
2         10  2.33  2.002249  0.385806